apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: dyir67dwt-nodejs 
  janus-idp.io/tekton: dyir67dwt-nodejs
  backstage.io/kubernetes-id: dyir67dwt-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dyir67dwt-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml